# Generated by Django 6.0.3 on 2026-03-26 16:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationTown', models.CharField(max_length=30)),
                ('locationNeighborhood', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
