# Generated by Django 6.0.3 on 2026-03-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_title'),
    ]

    operations = [
    ]
